In [1]:
import numpy as np
import pandas as pd
import pickle


In [2]:

ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
model = pickle.load(open('models/model.pkl','rb'))

In [3]:
test_input = np.array([2,'male',31.0,0,0,11.10,'S'],dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 11.1, 'S']], dtype=object)

In [5]:
test_input[:,1]

array(['male'], dtype=object)

In [6]:
test_input[:,-1]

array(['S'], dtype=object)

In [7]:
x_test_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/home/shohel/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [8]:
x_test_sex

array([[1.]])

In [9]:
x_test_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

/home/shohel/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/home/shohel/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:170: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


In [10]:
x_test_embarked

array([[0.]])

In [11]:
test_input_age = test_input[:,2].reshape(1,1)

In [12]:
test_input_transformed = np.concatenate((test_input[:,[0,2,3,4,5]],x_test_sex,test_input_age,x_test_embarked),axis=1)

In [13]:
test_input_transformed

array([[2, 31.0, 0, 0, 11.1, 1.0, 31.0, 0.0]], dtype=object)

In [14]:
model.predict(test_input_transformed)

array([0])